name: com.example.simple_app
description: A simple Flutter application with a login screen and a home screen using the Cubit pattern for state management.
version: 1.0.0
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3

dev_dependencies:
  bloc_test: ^9.1.7
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true